# ADD MODE CREATOR IF CREATING ACCOUNT AS CREATOR
### SIGN UP
POST http://localhost:4000/api/v1/auth/signup?mode=CREATOR HTTP/1.1
content-type: application/json

{
    "fullName": "Saloni Mishra",
    "email": "saloni@gmail.com",
    "password": "saloni@gmail.com",
    "roleId": "672f3450650e060d5f321dfb",
    "permissions": []
}


### LOGIN
POST http://localhost:4000/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "khankhalid1743@gmail.com",
    "password": "khankhalid1743@gmail.com"
}


### CURRENT USER
GET http://localhost:4000/api/v1/auth/current-user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzIxMDA5MzEsInVzZXJJRCI6IjY3MzA3MDJlZGUwMDVkYmI4ZTIxN2NjOCJ9.lPZlp9KNd5SibDDSUeIxnv_rD8s6SNoMlH_R0ZJlouc


### GENERATE WS TOKEN
GET http://localhost:4000/api/v1/auth/ws-token HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzE4NjQwMjEsInVzZXJJRCI6IjY3MzA3MDJlZGUwMDVkYmI4ZTIxN2NjOCJ9.iAg5Ms125iBzqGLRtaxooWmkbezF2TpPNBF-whvoAl0


### GET USER BY ID
GET http://localhost:4000/api/v1/auth/get/672c78151cede4084423180f HTTP/1.1
